// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voijthqwrvpumkkhfxmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaWp0aHF3cnZwdW1ra2hmeG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODY0ODQsImV4cCI6MjA3NDY2MjQ4NH0.Hx9MJq627eE2we5wQpi0rKnVGVjjeyUozgaNpDtAoqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
